### ISSUE TITLE
browse-at-remote/get-remote-type: Sorry, not sure what to do with repo ‘(nil . https://nil/nil)’

### ISSUE THREAD

**Issue by hlissner** [rmuslimov/browse-at-remote#17]
Occurs after running `browse-at-remote/browse` or `browse-at-remote/to-clipboard`. Tested in 5 different repos (some clean, some dirty).

## Backtrace
```
Debugger entered--Lisp error: (error "Sorry, not sure what to do with repo ‘(nil . https://nil/nil)’")
  signal(error ("Sorry, not sure what to do with repo ‘(nil . https://nil/nil)’"))
  error("Sorry, not sure what to do with repo `(nil . https://nil/nil)'")
  browse-at-remote/get-remote-type((nil . "https://nil/nil"))
  browse-at-remote/file-url("/Volumes/hlissner/.emacs.d/init.el" 4276)
  browse-at-remote/get-url()
  browse-at-remote/browse()
  (if bang (message "Url copied to clipboard: %s" (browse-at-remote/to-clipboard)) (browse-at-remote/browse))
  narf:git-remote-browse(nil nil)
  funcall-interactively(narf:git-remote-browse nil nil)
  call-interactively(narf:git-remote-browse)
  evil-ex-call-command(nil #("browse" 0 1 (ex-index 1) 1 2 (ex-index 2) 2 3 (ex-index 3) 3 4 (ex-index 4) 4 5 (ex-index 5) 5 6 (ex-index 6)) nil)
  eval((evil-ex-call-command nil #("browse" 0 1 (ex-index 1) 1 2 (ex-index 2) 2 3 (ex-index 3) 3 4 (ex-index 4) 4 5 (ex-index 5) 5 6 (ex-index 6)) nil))
  evil-ex-execute(#("browse" 0 1 (ex-index 1) 1 2 (ex-index 2) 2 3 (ex-index 3) 3 4 (ex-index 4) 4 5 (ex-index 5) 5 6 (ex-index 6)))
  evil-ex(nil)
  funcall-interactively(evil-ex nil)
  call-interactively(evil-ex nil nil)
  command-execute(evil-ex)
```

## Details

From inside `browse-at-remote/remote-ref` in one of my clean repos.

| letvar              | expression          | return value |
| ------------------ | ---------------------- | --------------- |
| `local-branch` | `(vc-git-working-revision ".")` | `c9833d9b82333282ee300ccd333b2e2094efb575` |
| `remote` | `(and local-branch (browse-at-remote/get-from-config (format "branch.%s.remote" local-branch)))` | `""` |
| `remote` | `(when remote (browse-at-remote/get-remote-url remote))` | `""` |
| `remote-branch` | `(s-chop-prefix "refs/heads/" (browse-at-remote/get-from-config (format "branch.%s.merge" local-branch)))` | `""` |

Running Emacs 25.1.50.1 on Mac OSX 10.10. I've tested this with `emacs -Q` and will try it on an earlier version of emacs once I get home.

**Comment by rmuslimov** [comment]
I guess this may happen only if you are on particular commit instead of being on HEAD of some branch. 
If this is true - I'm not sure which page should be open. AFAIK, we can't open page on github showing file at file at particular commit ( we can open current version of file in branch or particular commit). 

Decision for now, is move to HEAD and everything should work as expected. I added message in attached commit. 

Please, let me know if I'm wrong or you can suggest another approach to solve this. 

Thanks!

**Comment by hlissner** [comment]
Actually, I have tested on repos that are on HEAD of master, and I still get a id rather than a branch name. This doesn't seem to happen in Emacs 24.5 though. Maybe something has changed in `vc-git-working-revision` between 24.5 and 25.1? 

It returns `"c9833d9b82333282ee300ccd333b2e2094efb575"` in 25.1 and `"master"` in 24.5.

I'll look into it more after the holidays.

**Comment by rmuslimov** [comment]
@hlissner you're right. Thanks for catching this! I've updated implementation of browse-at-remote/remote-ref function and now it should work fine with latest emacs.

**Comment by hlissner** [comment]
Excellent! This solves the problem, thanks!

**Comment by j0ni** [comment]
This is happening for me with Emacs version 26.0.50 (`master` from about 5 days ago). @rmuslimov would you prefer a fresh issue?

**Comment by rmuslimov** [comment]
@j0ni I haven't heard about newest 26.x version so far. Will check in next spare minute. However, if you can file new issue with your details will be great. thanks!

**Comment by j0ni** [comment]
@rmuslimov sweet, will do.
