### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by blak3mill3r** [rmuslimov/browse-at-remote#2]
When I call `browse-at-remote` from a buffer viewing a file in a github repo, here's what I get:

```
Symbol's function definition is void: nil
```

Unfortunately I can't debug this problem (yet) since I am very new to emacs lisp. I don't even know how to get more information than the above status line, like which symbol's function definition is void, or where evaluation was at the time...

**Comment by rmuslimov** [comment]
@blak3mill3r it seems to me that you origin doesn't much regex pattern, or misconfigured. Can you please share output of this command executed in your github repo: 

```shell
git config --get remote.origin.url
```
