### ISSUE TITLE
github enterprise branch producing wrong-type-argument stringp nil

### ISSUE THREAD

**Issue by mstorus** [rmuslimov/browse-at-remote#20]
When I try to `M-x browse-at-remote` from a github enterprise non-master branch, I get the following error.

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  compare-strings("git" nil nil nil 0 3 nil)
  string-prefix-p("git" nil nil)
  s-starts-with\?("git" nil)
  browse-at-remote/get-url-from-remote(nil)
  browse-at-remote/file-url("/Users/me/code/my-lib-js/lib/file.js" 1)
  browse-at-remote/get-url()
  browse-at-remote()
  call-interactively(browse-at-remote record nil)
  command-execute(browse-at-remote record)
  execute-extended-command(nil "browse-at-remote")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

I already ran `git config --add browseAtRemote.type "github"` from the project root.

Any thoughts?

**Comment by rmuslimov** [comment]
I have something similar everytime when my local branch doesn't exists on server and `browse-at-remote` which branch select on github. May be your case the same?

**Comment by mstorus** [comment]
In my case the branch does exist on the remote server

**Comment by rmuslimov** [comment]
Unfortunately, I don't know so far - how to get name of the branch on origin - if it doesn't exist on remote.

**Comment by rmuslimov** [comment]
@mstorus can you please check if you case has been fixed by commit in #20

**Comment by mstorus** [comment]
@rmuslimov yes, it works now! thanks @Wilfred

**Comment by Wilfred** [comment]
Great :)
