### ISSUE TITLE
Naming conventions and obsolete alias warning

### ISSUE THREAD

**Issue by purcell** [rmuslimov/browse-at-remote#24]
Hey! Thanks for `browse-at-remote` -- it's a really useful package.

I noticed that calling `browse-at-remote` (ie. the main useful command in the package) produces an obsolete alias warning, telling me to instead call `browse-at-remote/browse`.

That seems clunky for two reasons: firstly, it's unnecessarily long and redundant, and secondly, `/` is not a standard separator for elisp symbols.

According to the [official elisp conventions](https://www.gnu.org/s/emacs/manual/html_node/elisp/Coding-Conventions.html), the prefix should be `browse-at-remote-` in this case, *particularly* for public symbols such as command names. `/` has come from emacs users who work with Clojure, but we should all be consistently using the established conventions for each language so that the community can collaborate as smoothly as possible.

I hope you'll consider renaming the affected symbols, and if you'd like me to submit a corresponding pull request I'd be more than happy to do so.

**Comment by rmuslimov** [comment]
Steve, yeah, I'm doing more clojure jobs last few months, and took that convention to this emacs lisp project. Agree with you, will fix the naming later this week, 

Thanks, for explanation,

**Comment by purcell** [comment]
Awesome, thanks - keep up the good work! :-)

**Comment by rmuslimov** [comment]
I hope this will work

**Comment by purcell** [comment]
LGTM - thanks!
