### ISSUE TITLE
remote-url-to-clipboard

### ISSUE THREAD

**Issue by ananthakumaran** [rmuslimov/browse-at-remote#3]
Could you add a function which is similar to browse-at-remote, but puts the url into clipboard instead of opening the url. Most of the time I just want to paste the url in the issue tracker or some other place

I am rebinding browse-url in my local config to get the same effect.
````lisp
(defun remote-url-to-clipboard ()
  (interactive)
  (flet ((browse-url (url &rest args)
                     (kill-new url)))
    (browse-at-remote)))
````

**Comment by rmuslimov** [comment]
Agree, I found myself doing same from time to time. please check my latest changes. Thanks!

**Comment by ananthakumaran** [comment]
Thanks. Works great.
