### ISSUE TITLE
Support GitHub Enterprise

### ISSUE THREAD

**Issue by env0der** [rmuslimov/browse-at-remote#6]
Would be very nice. For example ```git config --get remote.origin.url``` returns ```git@source.acme.com:super-team/awesome-project.git```

We can assume that the repo url on github enterprise is https://source.acme.com/super-team/awesome-project

Reasonable? I can try to implement this feature later this week.

**Comment by rmuslimov** [comment]
Yep, sounds good. However, I'm not sure how to understand which system we working with? github or bitbucket? Right now, we get this from url. So, if url is custom how will we know?

**Comment by env0der** [comment]
How about letting user put it to git config for the given repository? For example:
```git config --add browseAtRemote.type "github"```
Then we can get it via:
```git config browseAtRemote.type```

**Comment by rmuslimov** [comment]
Yep, this looks good. So, we can try to get this value first, if it's not defined, we will fallback to retrieve remote type from url. If you have time and desire to implement this feature - it will be great! Thanks!

**Comment by env0der** [comment]
Yes, I would like to contribute. However, I would be able to do it not sooner than in 2 weeks. Please leave this ticket open if it's fine for you.

**Comment by rmuslimov** [comment]
@env0der np, thanks!

**Comment by rmuslimov** [comment]
Thanks @env0der! Feature successfully landed.
