### ISSUE TITLE
Tag version 0.14.0

### ISSUE THREAD

**Issue by lafrenierejm** [rmuslimov/browse-at-remote#65]
Commit 771a3079e27f397d2f5a9470b945980fa68ee048 bumped the package's version to 0.14.0, but the latest tag is still 0.10.0.  Can 0.14.0 be tagged in git?  This would help with packaging efforts.

**Comment by rmuslimov** [comment]
Hm, I pushed tag to github a bit later than that commit. Now it's visible. Anything else needs to be done?

**Comment by lafrenierejm** [comment]
rmuslimov <notifications@github.com> writes:
> Hm, I pushed tag to github a bit later than that commit. Now 
> it's visible. Anything else needs to be done?

Nope!  I see it now.  It just hadn't propagated yet when I was 
looking.

This issue can safely be closed.  Thanks for the quick response. 
:)

--
Joseph LaFreniere
