### ISSUE TITLE
`apply: Wrong number of arguments: #<subr cons>, 1` when tracking local branches

### ISSUE THREAD

**Issue by terlar** [rmuslimov/browse-at-remote#69]
If you are tracking a local branch (`remote = .`) the command fails with the following error:
```
apply: Wrong number of arguments: #<subr cons>, 1
```
This is due to the `remote-and-branch` being just `master` for example instead of `origin/master`.

This happens if you use the configuration `autosetupmerge = always` and do a `git checkout -b newbranch`. Then it will track whatever branch you branched of from.

Not sure how this should be tackled, but perhaps use the remote for the local branch you target.

**Comment by zenspider** [comment]
I'm getting hit by this as well.. in my case `"main\n"`... it's bad enough I might need to turn the config off until this bug is figured out.
