### ISSUE TITLE
Remote's with underscores do not work

### ISSUE THREAD

**Issue by chrismccord** [rmuslimov/browse-at-remote#8]
Thanks for this great little package! It seems remotes containing underscores fail to parse, i.e.:

    Origin repo parsing failed: git@github.com:phoenixframework/phoenix_html.git

**Comment by rmuslimov** [comment]
Thanks, @chrismccord! Are you sure you pulled last version from melpa ( or github if you installed from source), I just tried to reproduce and it worked fine on my local installation? I just fixed issue with underscores few days ago, so should working ok

**Comment by chrismccord** [comment]
I should have checked the commits. All is working after updating. Thanks!
